---
include:
  # Generic pipeline description for all stages
  - "pipelines/pipeline.yaml"

# Stage-specific variables
variables:
  DEPLOY_ENV: "int"
  STAGE_ENV: "dev"
  LAP_TEST_DISABLE: "false"
  TRIGGER_BUILD_MANUALLY: "false"
