---
include:
  # Generic pipeline description for all stages
  - "pipelines/pipeline.yaml"

# Stage-specific variables
variables:
  DEPLOY_ENV: "int"
  STAGE_ENV: "dev"
  LAP_TEST_DISABLE: "false"
  TRIGGER_BUILD_MANUALLY: "false"
  PROJECT_RUNNER_TAG: "eks-integration"
  BASE_SERVICE_URL: "https://${VERSION_ENV}.bbpneo-iat.cnp-test.comp.db.de"
  SERVICE_URL: "https://${VERSION_ENV}.bbpneo-int.svc.cluster.local:443/actuator/info"
  SONARQUBE_PROJECT_KEY: "${CI_PROJECT_NAME}---Masterbranch"
  STAGE: "manual"
