---
include:
  - "/pipelines/stages/stage-artifacts.yaml"
  - "/pipelines/trivy/trivy.yaml"
  - "/pipelines/stages/deployment.yaml"
  - "/pipelines/stages/bizhub.yaml"
  - "/pipelines/security/syft.yaml"
  - "/pipelines/security/grant.yaml"
  - "/pipelines/security/grype.yaml"

# Stage-specific variables
variables:
  SOURCE_DOCKER_REPO: $DEV_DOCKER_REPO
  TARGET_DOCKER_REPO: $AU_DOCKER_REPO
  SOURCE_IMAGE_TAG: "$CI_COMMIT_REF_NAME-int-$CI_COMMIT_SHORT_SHA"
  TARGET_IMAGE_TAG: "$CI_COMMIT_REF_NAME-au-$CI_COMMIT_SHORT_SHA"
  ARTIFACT_NAME: $CI_PROJECT_NAME
  CI_REGISTRY: "${AU_DOCKER_REPO}.bahnhub.tech.rz.db.de"

stages:
  - .pre
  - stage-artifacts
  - security-scan
  - argo-cd-deploy
  - bizhub-deploy
  - dynamic-test
  - .post

Print Variables:
  stage: stage-artifacts
  tags:
    - $PROJECT_RUNNER_TAG
  image: ${PROD_DOCKER_REPO}.bahnhub.tech.rz.db.de/basis-pipeline-image:version-3
  script:
    - echo ${BIZHUB_DISABLE}
    - echo ${BIZHUB_VISIBILITY_TYPE}
    - echo ${BIZHUB_VISIBILITY_ORGS}
    - echo ${BIZHUB_SUBSCRIBE_ORGS}
    - echo $DEPLOY_ENV
    - echo $STAGE_ENV
    - echo $LAP_TEST_DISABLE
    - echo $TRIGGER_BUILD_MANUALLY
    - echo $PROJECT_RUNNER_TAG
    - echo $VERSION_ENV
    - echo $BASE_SERVICE_URL
    - echo $SERVICE_URL
    - echo $STAGE
    - echo $KANIKO_IMAGE_TAG
    - echo $NAMESPACE
    - echo $GIT_REPO_SSH_URL
