---
include:
  - "/pipelines/settings.yaml"
  - "/pipelines/stages/stage-artifacts.yaml"
  - "/pipelines/trivy/trivy.yaml"
  - "/pipelines/stages/deployment.yaml"
  - "/pipelines/stages/bizhub.yaml"

# Stage-specific variables
variables:
  STAGE_ENV: "au"
  PROJECT_RUNNER_TAG: "eks-au"
  SOURCE_DOCKER_REPO: $DEV_DOCKER_REPO
  TARGET_DOCKER_REPO: $AU_DOCKER_REPO
  SOURCE_IMAGE_TAG: "$CI_COMMIT_REF_NAME-int-$CI_COMMIT_SHORT_SHA"
  TARGET_IMAGE_TAG: "$CI_COMMIT_REF_NAME-au-$CI_COMMIT_SHORT_SHA"
  ARTIFACT_NAME: $CI_PROJECT_NAME
  CI_REGISTRY: "${AU_DOCKER_REPO}.bahnhub.tech.rz.db.de"

stages:
  - .pre
  - stage-artifacts
  - security-scan
  - argo-cd-deploy
  - bizhub-deploy
  - dynamic-test
  - .post
