---
include:
  - project: "moqap/modules"
    ref: "12.0.1"
    file:
      - "/artifactory/download_artifacts_dir.yml" #gibt es noch nicht in den includes muss in pipeline.yaml hinterlegt werden
      - "/artifactory/upload_artifacts_dir.yml"
      - "/lint/dockerfile/lint_dockerfile.yml"
      - "/eks/kaniko/kaniko.yml"
  - "/pipelines/stages/codeanalysis.yaml"
  - "/pipelines/stages/build-jar.yaml"
  - "/pipelines/stages/secrets-scan.yaml"

stages:
  - .pre
  - build-jar
  - static-codeanalysis
  - .post

Print Variables:
  stage: build-jar
  tags:
    - $PROJECT_RUNNER_TAG
  image: ${PROD_DOCKER_REPO}.bahnhub.tech.rz.db.de/basis-pipeline-image:version-3.3-multiarch
  script:
    - echo $DEPLOY_ENV
    - echo $STAGE_ENV
    - echo $PROJECT_RUNNER_TAG
    - echo $GIT_REPO_SSH_URL
    - echo $IS_COMMONLIB
