---
include:
  - project: "moqap/modules"
    ref: "11.3.0"
    file:
      - "/artifactory/download_artifacts_dir.yml" #gibt es noch nicht in den includes muss in pipeline.yaml hinterlegt werden
      - "/artifactory/upload_artifacts_dir.yml"
      - "/lint/dockerfile/lint_dockerfile.yml"
      - "/eks/kaniko/kaniko.yml"
  - "/pipelines/stages/codeanalysis.yaml"
  - "/pipelines/stages/build-jar.yaml"
  - "/pipelines/stages/release-script.yaml"
  - "/pipelines/stages/secrets-scan.yaml"

stages:
  - .pre
  - build-jar
  - static-codeanalysis
  - release
  - .post
