---
include:
  - "/pipelines/templates/moqap_templates.yml"

stages:
  - .pre
  - bizhub-deploy
  - .post

variables:
  # "cnp/bbpneo/02-ops/moqap"
  CURRENT_VERSION: "V2.0"
  AWS_SM_SECRET_PATH: "/runner/secrets/gitlab-runner-secret"
  BIZHUB_CONNECT_CONFIG: "bizhub/connect.yaml"

Deployment BizHub dev:
  stage: bizhub-deploy
  variables:
    DEPLOY_ENV: "dev"
    STAGE_ENV: "dev"
    VERSION_ENV: "${CI_PROJECT_NAME}-${DEPLOY_ENV}"
    BASE_SERVICE_URL: "https://${VERSION_ENV}.bbpneo-iat.cnp-test.comp.db.de"
    SERVICE_URL: "https://${VERSION_ENV}.bbpneo-dev-babedas.svc.cluster.local:443/actuator/info"
    STAGE: "review"
    PROJECT_RUNNER_TAG: "eks-entwicklung"
    BIZHUB_VISIBILITY_TYPE: "${DEV_BIZHUB_VISIBILITY_TYPE}"
    BIZHUB_VISIBILITY_ORGS: "${DEV_BIZHUB_VISIBILITY_ORGS}"
    BIZHUB_SUBSCRIBE_ORGS: "${DEV_BIZHUB_SUBSCRIBE_ORGS}"
  trigger:
    include:
      - project: "cnp/bbpneo/02-ops/moqap"
        ref: "$CURRENT_VERSION"
        file: "/pipelines/bizhub/bizhub-v3-api.yaml"
    strategy: depend
  when: manual

Deployment BizHub int:
  stage: bizhub-deploy
  variables:
    DEPLOY_ENV: "int"
    STAGE_ENV: "int"
    VERSION_ENV: "${CI_PROJECT_NAME}-${DEPLOY_ENV}"
    BASE_SERVICE_URL: "https://${VERSION_ENV}.bbpneo-iat.cnp-test.comp.db.de"
    SERVICE_URL: "https://${VERSION_ENV}.bbpneo-int.svc.cluster.local:443/actuator/info"
    STAGE: "manual"
    PROJECT_RUNNER_TAG: "eks-integration"
    BIZHUB_VISIBILITY_TYPE: "${INT_BIZHUB_VISIBILITY_TYPE}"
    BIZHUB_VISIBILITY_ORGS: "${INT_BIZHUB_VISIBILITY_ORGS}"
    BIZHUB_SUBSCRIBE_ORGS: "${INT_BIZHUB_SUBSCRIBE_ORGS}"
  trigger:
    include:
      - project: "cnp/bbpneo/02-ops/moqap"
        ref: "${CURRENT_VERSION}"
        file: "/pipelines/bizhub/bizhub-v3-api.yaml"
    strategy: depend
  when: manual

Deployment BizHub lup:
  stage: bizhub-deploy
  variables:
    DEPLOY_ENV: "lup"
    STAGE_ENV: "lup"
    VERSION_ENV: "${CI_PROJECT_NAME}-${DEPLOY_ENV}"
    BASE_SERVICE_URL: "https://${VERSION_ENV}.bbpneo-iat.cnp-test.comp.db.de"
    SERVICE_URL: "https://${VERSION_ENV}.bbpneo-lup.svc.cluster.local:443/actuator/info"
    STAGE: "lup"
    PROJECT_RUNNER_TAG: "eks-lup"
    BIZHUB_VISIBILITY_TYPE: "${LUP_BIZHUB_VISIBILITY_TYPE}"
    BIZHUB_VISIBILITY_ORGS: "${LUP_BIZHUB_VISIBILITY_ORGS}"
    BIZHUB_SUBSCRIBE_ORGS: "${LUP_BIZHUB_SUBSCRIBE_ORGS}"
  trigger:
    include:
      - project: "cnp/bbpneo/02-ops/moqap"
        ref: "${CURRENT_VERSION}"
        file: "/pipelines/bizhub/bizhub-v3-api.yaml"
    strategy: depend
  when: manual

Deployment BizHub au:
  stage: bizhub-deploy
  variables:
    DEPLOY_ENV: "au"
    STAGE_ENV: "au"
    VERSION_ENV: "${CI_PROJECT_NAME}-${DEPLOY_ENV}"
    BASE_SERVICE_URL: "https://${VERSION_ENV}.bbpneo-iat.cnp-test.comp.db.de"
    SERVICE_URL: "https://${VERSION_ENV}.bbpneo-au.svc.cluster.local:443/actuator/info"
    STAGE: "at"
    PROJECT_RUNNER_TAG: "eks-abnahme"
    BIZHUB_VISIBILITY_TYPE: "${AU_BIZHUB_VISIBILITY_TYPE}"
    BIZHUB_VISIBILITY_ORGS: "${AU_BIZHUB_VISIBILITY_ORGS}"
    BIZHUB_SUBSCRIBE_ORGS: "${AU_BIZHUB_SUBSCRIBE_ORGS}"
  trigger:
    include:
      - project: "cnp/bbpneo/02-ops/moqap"
        ref: "${CURRENT_VERSION}"
        file: "/pipelines/bizhub/bizhub-v3-api.yaml"
    strategy: depend
  when: manual

Deployment BizHub prod:
  stage: bizhub-deploy
  variables:
    DEPLOY_ENV: "prod"
    STAGE_ENV: "prod"
    VERSION_ENV: "${CI_PROJECT_NAME}-${DEPLOY_ENV}"
    BASE_SERVICE_URL: "https://${VERSION_ENV}.bbpneo-iat.cnp-test.comp.db.de"
    SERVICE_URL: "https://${VERSION_ENV}.bbpneo-prod.svc.cluster.local:443/actuator/info"
    STAGE: "prod"
    PROJECT_RUNNER_TAG: "eks-produktion"
    BIZHUB_VISIBILITY_TYPE: "${PROD_BIZHUB_VISIBILITY_TYPE}"
    BIZHUB_VISIBILITY_ORGS: "${PROD_BIZHUB_VISIBILITY_ORGS}"
    BIZHUB_SUBSCRIBE_ORGS: "${PROD_BIZHUB_SUBSCRIBE_ORGS}"
  trigger:
    include:
      - project: "cnp/bbpneo/02-ops/moqap"
        ref: "${CURRENT_VERSION}"
        file: "/pipelines/bizhub/bizhub-v3-api.yaml"
    strategy: depend
  when: manual
