---
include:
  - "/pipelines/templates/moqap_templates.yml"

stages:
  - .pre
  - bizhub-deploy
  - .post

variables:
  # "cnp/bbpneo/02-ops/moqap"
  CURRENT_VERSION: "V2.0"
  AWS_SM_SECRET_PATH: "/runner/secrets/gitlab-runner-secret"
  BIZHUB_CONNECT_CONFIG: "bizhub/connect.yaml"

Deployment BizHub dev:
  stage: bizhub-deploy
  rules:
    - if: $BIZHUB_DEPLOY_ONLY == "true"
      when: manual
      variables:
        DEPLOY_ENV: "dev"
        STAGE_ENV: "dev"
        VERSION_ENV: "${CI_PROJECT_NAME}-${DEPLOY_ENV}"
        BASE_SERVICE_URL: "https://${VERSION_ENV}.bbpneo-iat.cnp-test.comp.db.de"
        SERVICE_URL: "https://${VERSION_ENV}.bbpneo-dev-babedas.svc.cluster.local:443/actuator/info"
        STAGE: "review"
        PROJECT_RUNNER_TAG: "eks-entwicklung"
        BIZHUB_VISIBILITY_TYPE: "${DEV_BIZHUB_VISIBILITY_TYPE}"
        BIZHUB_VISIBILITY_ORGS: "${DEV_BIZHUB_VISIBILITY_ORGS}"
        BIZHUB_SUBSCRIBE_ORGS: "${DEV_BIZHUB_SUBSCRIBE_ORGS}"
  trigger:
    include:
      - project: "cnp/bbpneo/02-ops/moqap"
        ref: "$CURRENT_VERSION"
        file: "/pipelines/bizhub/bizhub-v3-api.yaml"
    strategy: depend
  when: manual

Deployment BizHub int:
  stage: bizhub-deploy
  rules:
    - if: $BIZHUB_DEPLOY_ONLY == "true"
      when: manual
      variables:
        DEPLOY_ENV: "int"
        STAGE_ENV: "int"
        VERSION_ENV: "${CI_PROJECT_NAME}-${DEPLOY_ENV}"
        BASE_SERVICE_URL: "https://${VERSION_ENV}.bbpneo-iat.cnp-test.comp.db.de"
        SERVICE_URL: "https://${VERSION_ENV}.bbpneo-int.svc.cluster.local:443/actuator/info"
        STAGE: "manual"
        PROJECT_RUNNER_TAG: "eks-integration"
        BIZHUB_VISIBILITY_TYPE: "${INT_BIZHUB_VISIBILITY_TYPE}"
        BIZHUB_VISIBILITY_ORGS: "${INT_BIZHUB_VISIBILITY_ORGS}"
        BIZHUB_SUBSCRIBE_ORGS: "${INT_BIZHUB_SUBSCRIBE_ORGS}"
  trigger:
    include:
      - project: "cnp/bbpneo/02-ops/moqap"
        ref: "${CURRENT_VERSION}"
        file: "/pipelines/bizhub/bizhub-v3-api.yaml"
    strategy: depend
  when: manual

Deployment BizHub lup:
  stage: bizhub-deploy
  rules:
    - if: $BIZHUB_DEPLOY_ONLY == "true"
      when: manual
      variables:
        DEPLOY_ENV: "lup"
        STAGE_ENV: "lup"
        VERSION_ENV: "${CI_PROJECT_NAME}-${DEPLOY_ENV}"
        BASE_SERVICE_URL: "https://${VERSION_ENV}.bbpneo-iat.cnp-test.comp.db.de"
        SERVICE_URL: "https://${VERSION_ENV}.bbpneo-lup.svc.cluster.local:443/actuator/info"
        STAGE: "lup"
        PROJECT_RUNNER_TAG: "eks-lup"
        BIZHUB_VISIBILITY_TYPE: "${LUP_BIZHUB_VISIBILITY_TYPE}"
        BIZHUB_VISIBILITY_ORGS: "${LUP_BIZHUB_VISIBILITY_ORGS}"
        BIZHUB_SUBSCRIBE_ORGS: "${LUP_BIZHUB_SUBSCRIBE_ORGS}"
  trigger:
    include:
      - project: "cnp/bbpneo/02-ops/moqap"
        ref: "${CURRENT_VERSION}"
        file: "/pipelines/bizhub/bizhub-v3-api.yaml"
    strategy: depend
  when: manual

Deployment BizHub au:
  stage: bizhub-deploy
  rules:
    - if: $BIZHUB_DEPLOY_ONLY == "true"
      when: manual
      variables:
        DEPLOY_ENV: "au"
        STAGE_ENV: "au"
        VERSION_ENV: "${CI_PROJECT_NAME}-${DEPLOY_ENV}"
        BASE_SERVICE_URL: "https://${VERSION_ENV}.bbpneo-iat.cnp-test.comp.db.de"
        SERVICE_URL: "https://${VERSION_ENV}.bbpneo-au.svc.cluster.local:443/actuator/info"
        STAGE: "at"
        PROJECT_RUNNER_TAG: "eks-abnahme"
        BIZHUB_VISIBILITY_TYPE: "${AU_BIZHUB_VISIBILITY_TYPE}"
        BIZHUB_VISIBILITY_ORGS: "${AU_BIZHUB_VISIBILITY_ORGS}"
        BIZHUB_SUBSCRIBE_ORGS: "${AU_BIZHUB_SUBSCRIBE_ORGS}"
  trigger:
    include:
      - project: "cnp/bbpneo/02-ops/moqap"
        ref: "${CURRENT_VERSION}"
        file: "/pipelines/bizhub/bizhub-v3-api.yaml"
    strategy: depend
  when: manual

Deployment BizHub prod:
  stage: bizhub-deploy
  rules:
    - if: $BIZHUB_DEPLOY_ONLY == "true"
      when: manual
      variables:
        DEPLOY_ENV: "prod"
        STAGE_ENV: "prod"
        VERSION_ENV: "${CI_PROJECT_NAME}-${DEPLOY_ENV}"
        BASE_SERVICE_URL: "https://${VERSION_ENV}.bbpneo-iat.cnp-test.comp.db.de"
        SERVICE_URL: "https://${VERSION_ENV}.bbpneo-prod.svc.cluster.local:443/actuator/info"
        STAGE: "prod"
        PROJECT_RUNNER_TAG: "eks-produktion"
        BIZHUB_VISIBILITY_TYPE: "${PROD_BIZHUB_VISIBILITY_TYPE}"
        BIZHUB_VISIBILITY_ORGS: "${PROD_BIZHUB_VISIBILITY_ORGS}"
        BIZHUB_SUBSCRIBE_ORGS: "${PROD_BIZHUB_SUBSCRIBE_ORGS}"
  trigger:
    include:
      - project: "cnp/bbpneo/02-ops/moqap"
        ref: "${CURRENT_VERSION}"
        file: "/pipelines/bizhub/bizhub-v3-api.yaml"
    strategy: depend
  when: manual

Print Variables:
  stage: bizhub-deploy
  tags:
    - $PROJECT_RUNNER_TAG
  image: ${PROD_DOCKER_REPO}.bahnhub.tech.rz.db.de/basis-pipeline-image:version-3
  script:
    - echo ${BIZHUB_DEPLOY_ONLY}
    - echo ${BIZHUB_CONNECT_CONFIG}
    - echo ${BIZHUB_DISABLE}
    - echo ${BIZHUB_VISIBILITY_TYPE}
    - echo ${BIZHUB_VISIBILITY_ORGS}
    - echo ${BIZHUB_SUBSCRIBE_ORGS}
    - echo ${DEPLOY_ENV}
    - echo ${STAGE_ENV}
    - echo ${PROJECT_RUNNER_TAG}
    - echo ${VERSION_ENV}
    - echo ${BASE_SERVICE_URL}
    - echo ${SERVICE_URL}
    - echo ${STAGE}
    - echo ${DEV_BIZHUB_VISIBILITY_TYPE}
    - echo ${DEV_BIZHUB_VISIBILITY_ORGS}
    - echo ${DEV_BIZHUB_SUBSCRIBE_ORGS}
    - echo ${DEV_B1_BIZHUB_VISIBILITY_TYPE}
    - echo ${DEV_B1_BIZHUB_VISIBILITY_ORGS}
    - echo ${DEV_B1_BIZHUB_SUBSCRIBE_ORGS}
    - echo ${INT_BIZHUB_VISIBILITY_TYPE}
    - echo ${INT_BIZHUB_VISIBILITY_ORGS}
    - echo ${INT_BIZHUB_SUBSCRIBE_ORGS}
    - echo ${AU_BIZHUB_VISIBILITY_TYPE}
    - echo ${AU_BIZHUB_VISIBILITY_ORGS}
    - echo ${AU_BIZHUB_SUBSCRIBE_ORGS}
    - echo ${LUP_BIZHUB_VISIBILITY_TYPE}
    - echo ${LUP_BIZHUB_VISIBILITY_ORGS}
    - echo ${LUP_BIZHUB_SUBSCRIBE_ORGS}
    - echo ${PROD_BIZHUB_VISIBILITY_TYPE}
    - echo ${PROD_BIZHUB_VISIBILITY_ORGS}
    - echo ${PROD_BIZHUB_SUBSCRIBE_ORGS}
