---
include:
  - project: "moqap/modules"
    ref: "11.2.2"
    file:
      - "/artifactory/download_artifacts_dir.yml"
  - "/pipelines/templates/moqap_templates.yml"
  - "/pipelines/settings.yaml"

.job_template: &job_template
  tags:
    - $PROJECT_RUNNER_TAG

variables:
  DEPLOY_ENV: "dev"
  STAGE_ENV: "dev"
  PROJECT_RUNNER_TAG: "eks-entwicklung"

stages:
  - .pre
  - find-jar
#  - build-image
#  - security-scan
#  - argo-cd-deploy
#  - bizhub-deploy
#  - .post

Find JAR:
  stage: find-jar
  extends: .Download-Artifacts
  <<: *job_template
  variables:
    ARTIFACTORY_PATH: "$MAVEN_REPO/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/Release-*/*/int/*.jar"
    TARGET_DIR: "artifacts"
    SECRETS:
      ARTIFACTORY_USER:RUNNER_ARTIFACTORY_USER,
      ARTIFACTORY_PASSWORD:RUNNER_ARTIFACTORY_PASSWORD
  before_script:
    - CURRENT_VERSION=$(cat gradle.properties | grep "version" | cut -d "=" -f2 | tr -dc '0-9.')
    - echo $CURRENT_VERSION
    - export ARTIFACTORY_PATH="$MAVEN_REPO/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/Release-$CURRENT_VERSION/*/int/*$CURRENT_VERSION.jar"
    - echo $ARTIFACTORY_PATH
  after_script:
    - touch artifatcs/cnp/test.jar
    - ls -Ral
    - find artifacts -name '*.jar' -print -ls
    - mv -i $(find artifacts -name '*.jar' -type f -exec ls -t1 {} + | head -1) artifacts
  artifacts:
    paths:
      - artifacts/*
