---
include:
  - project: "moqap/modules"
    ref: "11.2.1"
    file:
      - "/artifactory/download_artifacts_dir.yml"
  - "/pipelines/templates/moqap_templates.yml"
  - "/pipelines/settings.yaml"

.job_template: &job_template
  tags:
    - $PROJECT_RUNNER_TAG

variables:
  DEPLOY_ENV: "dev"
  STAGE_ENV: "dev"
  PROJECT_RUNNER_TAG: "eks-entwicklung"

stages:
  - .pre
  - find-jar
#  - build-image
#  - security-scan
#  - argo-cd-deploy
#  - bizhub-deploy
#  - .post

Find JAR:
  stage: find-jar
  extends: .Download-Artifacts
  <<: *job_template
  variables:
    ARTIFACTORY_PATH: "$MAVEN_REPO/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/Release-*/*/$CI_ENVIRONMENT_SLUG/*.jar"
    TARGET_DIR: "artifacts"
    SECRETS:
      ARTIFACTORY_USER:RUNNER_ARTIFACTORY_USER,
      ARTIFACTORY_PASSWORD:RUNNER_ARTIFACTORY_PASSWORD


