---
include:
  - project: "moqap/modules"
    ref: "11.2.2"
    file:
      - "/artifactory/download_artifacts_dir.yml"
      - "/eks/kaniko/kaniko.yml"
  - "/pipelines/templates/moqap_templates.yml"
  - "/pipelines/settings.yaml"

.job_template: &job_template
  tags:
    - $PROJECT_RUNNER_TAG

variables:
  DEPLOY_ENV: "dev"
  STAGE_ENV: "dev"
  PROJECT_RUNNER_TAG: "eks-entwicklung"

stages:
  - .pre
  - find-jar
  - build-image
#  - security-scan
#  - argo-cd-deploy
#  - bizhub-deploy
#  - .post

Find JAR:
  stage: find-jar
  extends: .Download-Artifacts
  <<: *job_template
  variables:
    ARTIFACTORY_PATH: "$MAVEN_REPO/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/Release-*/*/int/*.jar"
    TARGET_DIR: "artifacts"
    SECRETS:
      ARTIFACTORY_USER:RUNNER_ARTIFACTORY_USER,
      ARTIFACTORY_PASSWORD:RUNNER_ARTIFACTORY_PASSWORD
  before_script:
    - RELEASE_VERSION=$(cat gradle.properties | grep "version" | cut -d "=" -f2 | tr -dc '0-9.')
    - echo $RELEASE_VERSION
    - export ARTIFACTORY_PATH="$MAVEN_REPO/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/Release-$RELEASE_VERSION/*/int/*$RELEASE_VERSION.jar"
    - echo $ARTIFACTORY_PATH
  after_script:
    - RELEASE_VERSION=$(cat gradle.properties | grep "version" | cut -d "=" -f2 | tr -dc '0-9.')
    - echo $RELEASE_VERSION
    - find artifacts -name "*$RELEASE_VERSION.jar" -print -ls
    - mv -i $(find artifacts -name "*$RELEASE_VERSION.jar" -type f -exec ls -t1 {} + | head -1) artifacts
  artifacts:
    paths:
      - artifacts/*

Build Image:
  extends: .kaniko-build
  stage: build-image
  tags:
    - ${PROJECT_RUNNER_TAG}
  environment:
    name: ${DEPLOY_ENV}
  variables:
    KANIKO_SOURCE_REPO: ${PROD_DOCKER_REPO}
    SECRETS:
      CI_REGISTRY_USER:RUNNER_ARTIFACTORY_USER,
      CI_REGISTRY_PASSWORD:RUNNER_ARTIFACTORY_PASSWORD,
