include:
  - project: "moqap/modules"
    ref: "3.3.7"
    file:
      - "/artifactory/download_artifacts_dir.yml" #gibt es noch nicht in den includes muss in pipeline.yaml hinterlegt werden
  - "/pipelines/settings.yaml"

stages:
  - .pre
  - integrationtest


variables:
  ARTIFACT_NAME: $CI_PROJECT_NAME
  BASE_SERVICE_URL: $BASE_SERVICE_URL
  STAGE_ENV: "dev"
  PROPERTY_FILE: "ci.properties"
  RUNNER_MOUNT_PATH: "/tmp/${PROJECT_NAME}/${PROJECT_NAME}-${STAGE_ENV}/${PROJECT_NAME}-secret-claim-runner-${STAGE_ENV}"

.job_template: &job_template
  tags:
    - $PROJECT_RUNNER_TAG


Download Dependencies:
  extends: .Download-Artifacts
  stage: integrationtest
  <<: *job_template
  after_script:
    - mkdir -p ./artifacts/
    - cp download/cnp/dbds/bbpneo-3bds/testframework/master/int/artifacts/testframework-1.0-SNAPSHOT-all.jar  artifacts
  variables:
    ARTIFACTORY_PATH: "cna-3bservices-dev-docker-stage-local/cnp/dbds/bbpneo-3bds/testframework/master/int/artifacts/"
    TARGET_DIR: "download"
  artifacts:
    paths:
      - artifacts/*

Download Secrets:
  stage: integrationtest
  <<: *job_template
  image: docker-hub-remote.bahnhub.tech.rz.db.de/openjdk:19-jdk-alpine3.16
  script:
    - getSecret() { awk -F\""$1"\":\" '{if (NF > 1 ) print $2; else exit 1;}' < "$2" | awk -F"\",\"|\"}" '{print $1}' || FAIL="$3\n-> $4" ; }
    - echo "DEPLOY_ENV=$DEPLOY_ENV"
    - echo $RUNNER_MOUNT_PATH
    - export BETRAANTRAG_USERNAME=$(getSecret BETRAANTRAG_USERNAME $RUNNER_MOUNT_PATH $FAIL BETRAANTRAG_USERNAME)
    - echo $BETRAANTRAG_USERNAME
    - export BETRAANTRAG_PASSWORD=$(getSecret BETRAANTRAG_PASSWORD $RUNNER_MOUNT_PATH $FAIL BETRAANTRAG_PASSWORD)
    - echo $BETRAANTRAG_PASSWORD
    - export BETRAANTRAG_CLIENTSECRET=$(getSecret BETRAANTRAG_CLIENTSECRET $RUNNER_MOUNT_PATH $FAIL BETRAANTRAG_CLIENTSECRET)
    - echo $BETRAANTRAG_CLIENTSECRET
    - export BETRAANTRAG_CLIENTID=$(getSecret BETRAANTRAG_CLIENTID $RUNNER_MOUNT_PATH $FAIL BETRAANTRAG_CLIENTID)
    - echo $BETRAANTRAG_CLIENTID
    - echo $BASE_SERVICE_URL
    - touch ci.properties
    - ls
    - echo "BETRAANTRAG_USERNAME:$BETRAANTRAG_USERNAME" > $PROPERTY_FILE
    - echo "BETRAANTRAG_PASSWORD:$BETRAANTRAG_PASSWORD" >> $PROPERTY_FILE
    - cat $PROPPERTY_FILE
  artifacts:
    paths:
      - artifacts/*

Integration Test:
  stage: integrationtest
  <<: *job_template
  image: docker-hub-remote.bahnhub.tech.rz.db.de/openjdk:19-jdk-alpine3.16
  dependencies:
    - Download Dependencies
    - Download Secrets
  needs:
    - job: Download Dependencies
      artifacts: true 
    - job: Download Secrets
      artifacts: true
  script:
    - java -DDEPLOY_ENV=${DEPLOY_ENV} -DARTIFACT_NAME=${ARTIFACT_NAME} -DBASEURL=${BASE_SERVICE_URL} -jar ./artifacts/testframework-1.0-SNAPSHOT-all.jar
  artifacts:
    when: always
    name: "Cucumber Report"
    paths:
      - cucumber.html
      - cucumber.xml
    reports:
       junit: cucumber.xml