---
include:
  - project: "moqap/modules"
    ref: "5.0.0"
    file:
      - "/templates/moqap_templates.yml"

stages:
  - .pre
  - list_certificates
  - .post

# List Certificates
list_certificates:
  image: cna-bbpneo-prod-docker-stage-local.bahnhub.tech.rz.db.de/basis-pipeline-image:version-3
  tags:
    - eks-entwicklung
  stage: list_certificates
  variables:
    HTTP_PROXY: "http://webproxy.comp.db.de:8080"
    HTTPS_PROXY: "http://webproxy.comp.db.de:8080"
    NO_PROXY: ".amazon.com,.amazonaws.com,.aws.db.de,.cluster.local,.comp.db.de,.dbcs.db.de,.internal,.intranet-test.deutschebahn.com,.intranet.deutschebahn.com,.mail.db.de,.ose.db.de,.rz.db.de,.svc,.unix.db.de,10.193.0.1,127.0.0.1,169.254.169.254,dbcs-Maste-C6UND8OK4HFR-3e69d5b84ddd5126.elb.eu-central-1.amazonaws.com,ip-10-107-227-150.eu-central-1.compute.internal,localhost"
    http_proxy: "http://webproxy.comp.db.de:8080"
    https_proxy: "http://webproxy.comp.db.de:8080"
    no_proxy: ".amazon.com,.amazonaws.com,.aws.db.de,.cluster.local,.comp.db.de,.dbcs.db.de,.internal,.intranet-test.deutschebahn.com,.intranet.deutschebahn.com,.mail.db.de,.ose.db.de,.rz.db.de,.svc,.unix.db.de,10.193.0.1,127.0.0.1,169.254.169.254,dbcs-Maste-C6UND8OK4HFR-3e69d5b84ddd5126.elb.eu-central-1.amazonaws.com,ip-10-107-227-150.eu-central-1.compute.internal,localhost"
    AWS_SM_SECRET_PATH: "/runner/secrets/gitlab-runner-secret"
    KUBECONFIG_PATH: /tmp/kubeconfig.yaml
    DEPLOY_TEMPLATE: "appmesh.yaml"
    SECRETS:
      CNP_API_BBPNEO_IAT_KUBECONFIG:CNP_API_BBPNEO_IAT_KUBECONFIG,
      SSH_PRIVATE_KEY:RUNNER_SSH_KEY
  script:
    - !reference [.template secrets, script]
    ######################################################################################
    - export ARGOCD_SERVER=argocd.cnp.comp.db.de
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
    - ssh-add -l
    - ssh -T -o StrictHostKeyChecking=no git@ssh.git.tech.rz.db.de
    ######################################################################################
    - |
      git clone git@ssh.git.tech.rz.db.de:cnp/bbpneo/bbpneo-ops.git
      cd bbpneo-ops/bbpneo-iat/cnp-api
      ls -al $DEPLOY_TEMPLATE
    ######################################################################################
    - echo $KUBECONFIG_PATH
    - touch $KUBECONFIG_PATH
    - echo "$CNP_API_BBPNEO_IAT_KUBECONFIG" > $KUBECONFIG_PATH
    - export KUBECONFIG=$KUBECONFIG_PATH
    - kubectl config get-contexts
    - echo "Listing certificates..."
    - kubectl get certificates.cnp.comp.db.de -n bbpneo-iat --context cnp-api-iat-v4-zgjrp -o jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.status.resources.aws-certificate.externalName}{"\n"}{end}' -l cnp.comp.db.de/appmesh=dbds
    - export CERTIFICATE_ARNS=$(kubectl get certificates.cnp.comp.db.de -n bbpneo-iat --context cnp-api-iat-v4-zgjrp -o jsonpath='{range .items[*]}{.status.resources.aws-certificate.externalName},{end}' -l cnp.comp.db.de/appmesh=dbds | rev | cut -c2- | rev)
    - echo $CERTIFICATE_ARNS
    ######################################################################################
    - |
      - yq e -i '.spec.parameters.gateway.loadbalancer.sslCertificateARNs = strenv(CERTIFICATE_ARNS)' $DEPLOY_TEMPLATE
      cat $DEPLOY_TEMPLATE | grep -q "#updated on" && current_timestamp=`date +%s` &&  sed -i "s/#updated on \(.*\)/#updated on $(date +%s)/g" $DEPLOY_TEMPLATE || echo "#updated on `date +%s`" >> $DEPLOY_TEMPLATE
      cat $DEPLOY_TEMPLATE
