---
include:
  - project: "moqap/modules"
    ref: "10.0.0"
    file: "/trivy/trivy.yml"

.job_template: &job_template
  tags:
    - $PROJECT_RUNNER_TAG

stages:
  - .pre
  - security-scan
  - .post

Trivy Check Image:
  extends: .Trivy Scan
  stage: security-scan
  <<: *job_template
  variables:
    MQP_TRIVY_ADD_CMD: "--no-progress --timeout 30m --offline-scan --debug --scanners vuln"
    MQP_TRIVY_TARGET: "$CI_REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    MQP_TRIVY_COMPLIANCE_SCAN: false
    MQP_TRIVY_EXIT_CODE_HIGH: 2
    TRIVY_EXIT_CODE_HIGH: 2
    SECRETS:
      TRIVY_USERNAME:RUNNER_ARTIFACTORY_USER,
      TRIVY_PASSWORD:RUNNER_ARTIFACTORY_PASSWORD
  allow_failure:
      exit_codes: # User defined exit code
        - 2
