---
include:
  - project: "moqap/modules"
    ref: "9.0.0"
    file: "/trivy/trivy.yml"

.job_template: &job_template
  tags:
    - $PROJECT_RUNNER_TAG

stages:
  - .pre
  - security-scan
  - .post

Trivy Check Image:
  extends: .Trivy Scan
  stage: security-scan
  <<: *job_template
  variables:
    TRIVY_ADD_CMD: "--no-progress --timeout 30m --offline-scan --debug --scanners vuln"
    TRIVY_TARGET: "$CI_REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    MQP_TRIVY_EXIT_CODE_HIGH: 0
    SECRETS:
      TRIVY_USERNAME:RUNNER_ARTIFACTORY_USER,
      TRIVY_PASSWORD:RUNNER_ARTIFACTORY_PASSWORD,
  allow_failure: true
