---
include:
  - project: "moqap/modules"
    ref: "5.0.0"
    file:
      - "/eks/kaniko/kaniko.yml"
      - "/artifactory/stage_artifacts.yml"
  - "/pipelines/trivy/trivy-scanimage.yaml"
  - "/pipelines/settings.yaml"

variables:
  PROJECT_RUNNER_TAG: "eks-entwicklung"
  DEPLOY_ENV: "int"
  CI_REGISTRY: "${DEV_DOCKER_REPO}.bahnhub.tech.rz.db.de"
  CI_REGISTRY_USER: $ARTIFACTORY_USER
  CI_REGISTRY_PASSWORD: $ARTIFACTORY_PASSWORD
  KANIKO_IMAGE_TAG: $CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
  TRIVY_TARGET: "$CI_REGISTRY/$CI_PROJECT_NAME:$KANIKO_IMAGE_TAG"
  SOURCE_DOCKER_REPO: ${DEV_DOCKER_REPO}
  TARGET_DOCKER_REPO: "${PROD_DOCKER_REPO}"
  ARTIFACT_NAME: $CI_PROJECT_NAME

stages:
  - build-image
  - security-scan
  - stage-artifacts

Artifacts STAGE:
  extends: .kaniko-build
  stage: build-image
  tags:
    - ${PROJECT_RUNNER_TAG}
  environment:
    name: ${DEPLOY_ENV}
  before_script:
    - echo $DEV_DOCKER_REPO
    - echo $PROD_DOCKER_REPO
    - echo $CI_PIPELINE_SOURCE
    - echo $ARTIFACT_NAME
    - echo $SOURCE_PATH
    - echo $TARGET_PATH
    - echo $ARTIFACTORY_URL
    - echo $ARTIFACTORY_USER
    - echo $OPTIONS
    - echo $SOURCE_TAG
    - echo $TARGET_TAG

Promote STAGE:
  extends: .Stage-Artifacts
  stage: stage-artifacts
  tags:
    - ${PROJECT_RUNNER_TAG}
  before_script:
    - echo $CI_PIPELINE_SOURCE
    - echo $ARTIFACT_NAME
    - echo $SOURCE_PATH
    - echo $TARGET_PATH
    - echo $ARTIFACTORY_URL
    - echo $ARTIFACTORY_USER
    - echo $OPTIONS
    - echo $SOURCE_TAG
    - echo $TARGET_TAG
  variables:
    SOURCE_PATH: "$SOURCE_DOCKER_REPO"
    TARGET_PATH: "$TARGET_DOCKER_REPO"
    SOURCE_TAG: "$KANIKO_IMAGE_TAG"
    TARGET_TAG: "$imageVersion"
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: on_success

Promote STAGE dev repo:
  extends: .Stage-Artifacts
  stage: stage-artifacts
  tags:
    - ${PROJECT_RUNNER_TAG}
  before_script:
    - echo $CI_PIPELINE_SOURCE
    - echo $ARTIFACT_NAME
    - echo $SOURCE_PATH
    - echo $TARGET_PATH
    - echo $ARTIFACTORY_URL
    - echo $ARTIFACTORY_USER
    - echo $OPTIONS
    - echo $SOURCE_TAG
    - echo $TARGET_TAG
  variables:
    SOURCE_PATH: "$SOURCE_DOCKER_REPO"
    TARGET_PATH: "$SOURCE_DOCKER_REPO"
    SOURCE_TAG: "$KANIKO_IMAGE_TAG"
    TARGET_TAG: "$imageVersion"
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: on_success
