---
include:
  - project: "moqap/modules"
    ref: "10.0.0"
    file:
      - "/eks/kaniko/kaniko.yml"
      - "/artifactory/stage_artifacts.yml"
  - "/pipelines/trivy/trivy-scanimage.yaml"
  - "/pipelines/settings.yaml"

variables:
  PROJECT_RUNNER_TAG: "eks-entwicklung"
  DEPLOY_ENV: "int"
  CI_REGISTRY: "${DEV_DOCKER_REPO}.bahnhub.tech.rz.db.de"
  KANIKO_IMAGE_TAG: $CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
  TRIVY_TARGET: "$CI_REGISTRY/$CI_PROJECT_NAME:$KANIKO_IMAGE_TAG"
  SOURCE_DOCKER_REPO: ${DEV_DOCKER_REPO}
  TARGET_DOCKER_REPO: "${PROD_DOCKER_REPO}"
  ARTIFACT_NAME: $CI_PROJECT_NAME
  SECRETS:
    CI_REGISTRY_USER:RUNNER_ARTIFACTORY_USER,
    CI_REGISTRY_PASSWORD:RUNNER_ARTIFACTORY_PASSWORD,
    ARTIFACTORY_USER:RUNNER_ARTIFACTORY_USER,
    ARTIFACTORY_PASSWORD:RUNNER_ARTIFACTORY_PASSWORD

stages:
  - build-image
  - security-scan
  - stage-artifacts

Build Image:
  extends: .kaniko-build
  stage: build-image
  tags:
    - ${PROJECT_RUNNER_TAG}
  environment:
    name: ${DEPLOY_ENV}
  variables:
    KANIKO_SOURCE_REPO: ${PROD_DOCKER_REPO}
    SECRETS:
      CI_REGISTRY_USER:RUNNER_ARTIFACTORY_USER,
      CI_REGISTRY_PASSWORD:RUNNER_ARTIFACTORY_PASSWORD,

Promote STAGE prod repo:
  extends: .Stage-Artifacts
  stage: stage-artifacts
  tags:
    - ${PROJECT_RUNNER_TAG}
  variables:
    SOURCE_PATH: "$SOURCE_DOCKER_REPO"
    TARGET_PATH: "$TARGET_DOCKER_REPO"
    SOURCE_TAG: "$KANIKO_IMAGE_TAG"
    TARGET_TAG: "$imageVersion"
    SECRETS:
      ARTIFACTORY_USER:RUNNER_ARTIFACTORY_USER,
      ARTIFACTORY_PASSWORD:RUNNER_ARTIFACTORY_PASSWORD
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: on_success

Promote STAGE dev repo:
  extends: .Stage-Artifacts
  stage: stage-artifacts
  tags:
    - ${PROJECT_RUNNER_TAG}
  variables:
    SOURCE_PATH: "$SOURCE_DOCKER_REPO"
    TARGET_PATH: "$SOURCE_DOCKER_REPO"
    SOURCE_TAG: "$KANIKO_IMAGE_TAG"
    TARGET_TAG: "$imageVersion"
    SECRETS:
      ARTIFACTORY_USER:RUNNER_ARTIFACTORY_USER,
      ARTIFACTORY_PASSWORD:RUNNER_ARTIFACTORY_PASSWORD
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: on_success
