---
include:
  # Generic pipeline description for all stages
  - "pipelines/pipeline.yaml"

# Stage-specific variables
variables:
  DEPLOY_ENV: "dev"
  VERSION_ENV: "${CI_PROJECT_NAME}-dev-b1"
  STAGE_ENV: "dev"
  LAP_TEST_DISABLE: "true"
  TRIGGER_BUILD_MANUALLY: "true"
  PROJECT_RUNNER_TAG: "eks-entwicklung"
  BASE_SERVICE_URL: "https://${VERSION_ENV}.bbpneo-iat.cnp-test.comp.db.de"
  SERVICE_URL: "https://${VERSION_ENV}.bbpneo-dev-b1.svc.cluster.local:443/actuator/info"
  STAGE: "review"
