---
include:
  - project: "moqap/modules"
    ref: "3.3.5"
    file:
      - "/artifactory/upload_artifacts_dir.yml"
      - "/eks/kaniko/kaniko.yml"
  - "/pipelines/settings.yaml"
  - "/pipelines/stages/upload-artifacts.yaml"

variables:
  PROJECT_RUNNER_TAG: "eks-dev"
  DEPLOY_ENV: "int"
  DEV_DOCKER_REPO: "cna-3bservices-dev-docker-stage-local"
  CI_REGISTRY: "${DEV_DOCKER_REPO}.bahnhub.tech.rz.db.de"
  CI_REGISTRY_USER: $ARTIFACTORY_USER
  CI_REGISTRY_PASSWORD: $ARTIFACTORY_PASSWORD
  SOURCE_DOCKER_REPO: ${DEV_DOCKER_REPO}
  TARGET_DOCKER_REPO: "cna-3bservices-prod-docker-stage-local"
  ARTIFACT_NAME: $CI_PROJECT_NAME

stages:
  - build-jar
  - upload

---
Build Jar:
  stage: build-jar
  tags:
    - eks-dev
  image: docker-hub-remote.bahnhub.tech.rz.db.de/openjdk:19-jdk-alpine3.16
  script:
    - export GRADLE_OPTS="$GRADLE_OPTS_OWN"
    - echo $GRADLE_OPTS
    - ./gradlew clean build jacocoTestCoverageVerification bootJar
    - mkdir -p ./artifacts/
    - cp build/libs/*.jar ./artifacts/
  only:
    - branches
  artifacts:
    paths:
      - src/target/*
      - artifacts/*
      - .gradle/
  variables:
    GRADLE_OPTS_OWN: "-Xdebug -XshowSettings -Xdiag  -Dhttps.proxyHost=webproxy.comp.db.de -Dhttps.proxyPort=8080 -Dhttp.nonProxyHosts=*.tech.rz.db.de|*.dbcs.db.de|*.amazonaws.com|*.aws.db.de|*.cluster.local|*.internal|*.intranet-test.deutschebahn.com|*.intranet.deutschebahn.com|*.mail.db.de|*.ose.db.de|*.rz.db.de|*.svc|*.unix.db.de|127.0.0.1|dbcs-Maste-C6UND8OK4HFR-3e69d5b84ddd5126.elb.eu-central-1.amazonaws.com|ip-10-107-227-150.eu-central-1.compute.internal|localhost|*.comp.db.de"

---
Upload Artifacts STAGE:
  stage: upload
  extends: .Upload-Artifacts
  tags:
    - eks-dev
  only:
    - branches
  environment:
    name: ${DEPLOY_ENV}
  artifacts:
    paths:
      - artifacts/*
  dependencies:
    - Build Jar
  needs:
    - job: Build Jar
  variables:
    TARGET_PATH: "$DEV_DOCKER_REPO/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME/$CI_COMMIT_SHORT_SHA/$CI_ENVIRONMENT_SLUG/"
    ARTIFACTS_DIR: "artifacts"
    ARTIFACTORY_USER: $ARTIFACTORY_USER
    ARTIFACTORY_PASSWORD: $ARTIFACTORY_PASSWORD
    ARTIFACTORY_URL: "https://bahnhub.tech.rz.db.de/artifactory/"