---
include:
  - project: "moqap/modules"
    ref: "5.0.0"
    file:
      - "/artifactory/download_artifacts_dir.yml" #gibt es noch nicht in den includes muss in pipeline.yaml hinterlegt werden
      - "/artifactory/upload_artifacts_dir.yml"
      - "/eks/kaniko/kaniko.yml"
  - "/pipelines/settings.yaml"
  - "/pipelines/stages/integrationtest.yaml"

.job_template: &job_template
  tags:
    - $PROJECT_RUNNER_TAG

variables:
  PROJECT_RUNNER_TAG: "eks-entwicklung"
  DEV_DOCKER_REPO: "${DEV_DOCKER_REPO}"
  SOURCE_DOCKER_REPO: ${DEV_DOCKER_REPO}
  TARGET_DOCKER_REPO: "${PROD_DOCKER_REPO}"
  ARTIFACTORY_URL: "https://bahnhub.tech.rz.db.de/artifactory/"

stages:
  - .pre
  - build-jar
  - upload
  - integrationtest

Build Jar:
  stage: build-jar
  <<: *job_template
  image: docker-hub-remote.bahnhub.tech.rz.db.de/openjdk:19-jdk-alpine3.16
  script:
    - export GRADLE_OPTS="$GRADLE_OPTS_OWN"
    - echo $GRADLE_OPTS
    - chmod +x ./gradlew
    - ./gradlew clean jar
    - mkdir -p ./artifacts/
    - cp build/libs/*.jar ./artifacts/
  only:
    - branches
  artifacts:
    paths:
      - src/target/*
      - artifacts/*
      - .gradle/
  variables:
    GRADLE_OPTS_OWN: "-Xdebug -XshowSettings -Xdiag  -Dhttps.proxyHost=webproxy.comp.db.de -Dhttps.proxyPort=8080 -Dhttp.nonProxyHosts=*.tech.rz.db.de|*.dbcs.db.de|*.amazonaws.com|*.aws.db.de|*.cluster.local|*.internal|*.intranet-test.deutschebahn.com|*.intranet.deutschebahn.com|*.mail.db.de|*.ose.db.de|*.rz.db.de|*.svc|*.unix.db.de|127.0.0.1|dbcs-Maste-C6UND8OK4HFR-3e69d5b84ddd5126.elb.eu-central-1.amazonaws.com|ip-10-107-227-150.eu-central-1.compute.internal|localhost|*.comp.db.de"

Upload Artifacts:
  stage: upload
  <<: *job_template
  extends: .Upload-Artifacts
  only:
    - branches
  environment:
    name: ${DEPLOY_ENV}
  dependencies:
    - Build Jar
  needs:
    - job: Build Jar
  variables:
    TARGET_PATH: "$DEV_DOCKER_REPO/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME/$CI_ENVIRONMENT_SLUG/"