---
include:
  - project: "moqap/modules"
    ref: "12.0.1"
    file:
      - "/artifactory/download_artifacts_dir.yml"
      - "/artifactory/upload_artifacts_dir.yml"
      - "/artifactory/clean_artifactory.yml"
      - "/lint/dockerfile/lint_dockerfile.yml"
      - "/jmeter/jmeter.yml"
  - "/pipelines/stages/codeanalysis.yaml"
  - "/pipelines/stages/build-jar.yaml"
  - "/pipelines/stages/build-image.yaml"
  - "/pipelines/stages/upload-artifacts.yaml"
  - "/pipelines/stages/secrets-scan.yaml"
  - "/pipelines/trivy/trivy.yaml"
  - "/pipelines/security/syft.yaml"
  - "/pipelines/security/grant.yaml"
  # - "/pipelines/security/grype.yaml"
  - "/pipelines/defectDojo/defect-dojo.yaml"

stages:
  - .pre
  - build-jar
  - static-codeanalysis
  - build-image
  - upload
  - security-scan
  - report-upload
  - .post
