---
include:
  - "/pipelines/settings.yaml"
  - "/pipelines/stages/build-go.yaml"
  - "/pipelines/stages/build-go-image.yaml"
  - "/pipelines/stages/stage-artifacts.yaml"
  - "/pipelines/trivy/trivy.yaml"
  - "/pipelines/security/syft.yaml"
  - "/pipelines/security/grant.yaml"
  - "/pipelines/security/grype.yaml"
  - "/pipelines/defectDojo/defect-dojo.yaml"

variables:
  BUILD: "GO"
  PROJECT_RUNNER_TAG: "eks-entwicklung"
  DEPLOY_ENV: "dev"
  ARTIFACT_NAME: $CI_PROJECT_NAME
  SOURCE_DOCKER_REPO: ${DEV_DOCKER_REPO}
  TARGET_DOCKER_REPO: ${PROD_DOCKER_REPO}
  SOURCE_IMAGE_TAG: "$CI_COMMIT_REF_NAME-dev-$CI_COMMIT_SHORT_SHA"
  TARGET_IMAGE_TAG: "$imageVersion"
  BUILD_CMD: ""
  IS_UPDATE: false

stages:
  - .pre
  - build-go
  - build-go-image
  - security-scan
  - stage-artifacts
  - report-upload
  - .post

Print Variables:
  stage: build-go
  tags:
    - $PROJECT_RUNNER_TAG
  image: ${PROD_DOCKER_REPO}.bahnhub.tech.rz.db.de/basis-pipeline-image:version-3.3-multiarch
  script:
    - echo $DEPLOY_ENV
    - echo $STAGE_ENV
    - echo $PROJECT_RUNNER_TAG
    - echo $KANIKO_IMAGE_TAG
    - echo $SOURCE_IMAGE_TAG
    - echo $TARGET_IMAGE_TAG
    - echo $NAMESPACE
    - echo $IS_CRONJOB
    - echo $IS_COMMONLIB
    - echo $IS_PYTHONJOB
    - echo $IS_SOPSJOB
    - echo $BUILD_CMD
    - echo $IS_UPDATE
