---
include:
  - project: "moqap/modules"
    ref: "10.2.0"
    file:
      - "/eks/kaniko/kaniko.yml"
      - "/trivy/trivy.yml"
  - "/pipelines/settings.yaml"
  - "/pipelines/stages/build-go.yaml"
  - "/pipelines/stages/build-go-image.yaml"
  - "/pipelines/stages/stage-artifacts.yaml"
  - "/pipelines/trivy/trivy.yaml"

variables:
  BUILD: "GO"
  PROJECT_RUNNER_TAG: "eks-entwicklung"
  DEPLOY_ENV: "dev"
  SOURCE_DOCKER_REPO: ${DEV_DOCKER_REPO}
  TARGET_DOCKER_REPO: ${PROD_DOCKER_REPO}
  SOURCE_IMAGE_TAG: "$CI_COMMIT_REF_NAME-int-$CI_COMMIT_SHORT_SHA"
  TARGET_IMAGE_TAG: "$imageVersion"

stages:
  - .pre
  - build-go
  - build-go-image
  - security-scan
  - stage-artifacts
  - .post
