---
include:
  - project: "moqap/modules"
    ref: "10.2.0"
    file:
      - "/artifactory/download_artifacts_dir.yml" #gibt es noch nicht in den includes muss in pipeline.yaml hinterlegt werden
      - "/artifactory/upload_artifacts_dir.yml"
      - "/artifactory/clean_artifactory.yml"
      - "/eks/kaniko/kaniko.yml"
      - "/trivy/trivy.yml"
  - "/pipelines/settings.yaml"
  - "/pipelines/stages/build-go.yaml"
  - "/pipelines/stages/build-image.yaml"
  - "/pipelines/stages/upload-artifacts.yaml"
  - "/pipelines/trivy/trivy.yaml"

stages:
  - .pre
  - build-go
  - build-image
  - security-scan
  - .post
