---
include:
  - project: "moqap/modules"
    ref: "10.2.0"
    file:
      - "/eks/kaniko/kaniko.yml"
      - "/trivy/trivy.yml"
  - "/pipelines/settings.yaml"
  - "/pipelines/stages/build-go.yaml"
  - "/pipelines/stages/build-go-image.yaml"
  - "/pipelines/trivy/trivy.yaml"

stages:
  - .pre
  - build-go
  - build-go-image
  - security-scan
  - .post
