---
include:
  - project: "moqap/modules"
    ref: "11.3.0"
    file:
      - "/artifactory/download_artifacts_dir.yml"
      - "/artifactory/upload_artifacts_dir.yml"
      - "/artifactory/clean_artifactory.yml"
      - "/lint/dockerfile/lint_dockerfile.yml"
      - "/jmeter/jmeter.yml"
      - "/eks/kaniko/kaniko.yml"
  - "/pipelines/stages/codeanalysis.yaml"
  - "/pipelines/stages/build-jar.yaml"
  - "/pipelines/stages/build-image.yaml"
  - "/pipelines/stages/upload-artifacts.yaml"
  - "/pipelines/stages/deployment.yaml"
  - "/pipelines/stages/secrets-scan.yaml"
  - "/pipelines/stages/bizhub.yaml"
  - "/pipelines/trivy/trivy.yaml"
  - "/pipelines/stages/integrationtest.yaml"
  - "/pipelines/artifactory/clean_artifactory.yaml"
  - "/pipelines/security/syft.yaml"
  - "/pipelines/security/grant.yaml"
  - "/pipelines/security/grype.yaml"

stages:
  - .pre
  - build-jar
  - static-codeanalysis
  - build-image
  - upload
  - security-scan
  - argo-cd-deploy
  - bizhub-deploy
  - integrationtest
  - cleanup
  - .post

Print Variables:
  stage: build-jar
  tags:
    - $PROJECT_RUNNER_TAG
  image: ${PROD_DOCKER_REPO}.bahnhub.tech.rz.db.de/basis-pipeline-image:version-3
  script:
    - echo $DEV_BIZHUB_DISABLE
    - echo $DEV_BIZHUB_VISIBILITY_TYPE
    - echo $DEV_BIZHUB_VISIBILITY_ORGS
    - echo $DEV_BIZHUB_SUBSCRIBE_ORGS
    - echo $BIZHUB_DISABLE
    - echo $BIZHUB_VISIBILITY_TYPE
    - echo $BIZHUB_VISIBILITY_ORGS
    - echo $BIZHUB_SUBSCRIBE_ORGS
