---
include:
  - "/pipelines/settings.yaml"

variables:
  IS_COMMONLIB: "false"
  BIZHUB_DEPLOY_ONLY: "false"
  IMAGE_UPDATE: "false"

stages:
  - dev
  - int
  - au
  - lup
  - prod
  - bizhub
  - image-update

Entwicklungsumgebung:
  stage: dev
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH  != "development"  && $CI_COMMIT_BRANCH  !~ /^Release/ && ($CI_COMMIT_BRANCH =~ /^BBPT4/ || $CI_COMMIT_BRANCH =~ /^BABEDAS/ ) && $CI_COMMIT_TAG == null && $BIZHUB_DEPLOY_ONLY == "false" && $IMAGE_UPDATE == "false"
      when: always
      variables:
        BIZHUB_DISABLE: "${DEV_BIZHUB_DISABLE}"
        BIZHUB_VISIBILITY_TYPE: "${DEV_BIZHUB_VISIBILITY_TYPE}"
        BIZHUB_VISIBILITY_ORGS: "${DEV_BIZHUB_VISIBILITY_ORGS}"
        BIZHUB_SUBSCRIBE_ORGS: "${DEV_BIZHUB_SUBSCRIBE_ORGS}"
        DEPLOY_ENV: "dev"
        STAGE_ENV: "dev"
        LAP_TEST_DISABLE: "true"
        TRIGGER_BUILD_MANUALLY: "true"
        PROJECT_RUNNER_TAG: "eks-entwicklung"
        VERSION_ENV: "${CI_PROJECT_NAME}-${DEPLOY_ENV}"
        BASE_SERVICE_URL: "https://${VERSION_ENV}.bbpneo-iat.cnp-test.comp.db.de"
        SERVICE_URL: "https://${VERSION_ENV}.bbpneo-dev-babedas.svc.cluster.local:443/actuator/info"
        STAGE: "review"
        KANIKO_IMAGE_TAG: "${CI_COMMIT_REF_NAME}-${DEPLOY_ENV}-${CI_COMMIT_SHORT_SHA}"
  trigger:
    include:
      - project: "cnp/bbpneo/02-ops/moqap"
        ref: "$CURRENT_VERSION"
        file: "/pipelines/pipeline.yaml"
    strategy: depend

Entwicklungsumgebung B1:
  stage: dev
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH  != "development"  && $CI_COMMIT_BRANCH  !~ /^Release/ && ($CI_COMMIT_BRANCH =~ /^BBPT7/ || $CI_COMMIT_BRANCH =~ /^BONE/ ) && $CI_COMMIT_TAG == null && $IS_COMMONLIB == "false" && $BIZHUB_DEPLOY_ONLY == "false" && $IMAGE_UPDATE == "false"
      when: always
      variables:
        BIZHUB_DISABLE: "${DEV_B1_BIZHUB_DISABLE}"
        BIZHUB_VISIBILITY_TYPE: "${DEV_B1_BIZHUB_VISIBILITY_TYPE}"
        BIZHUB_VISIBILITY_ORGS: "${DEV_B1_BIZHUB_VISIBILITY_ORGS}"
        BIZHUB_SUBSCRIBE_ORGS: "${DEV_B1_BIZHUB_SUBSCRIBE_ORGS}"
        DEPLOY_ENV: "dev"
        STAGE_ENV: "dev"
        LAP_TEST_DISABLE: "true"
        TRIGGER_BUILD_MANUALLY: "true"
        PROJECT_RUNNER_TAG: "eks-entwicklung"
        VERSION_ENV: "${CI_PROJECT_NAME}-${DEPLOY_ENV}-b1"
        BASE_SERVICE_URL: "https://${VERSION_ENV}.bbpneo-iat.cnp-test.comp.db.de"
        SERVICE_URL: "https://${VERSION_ENV}.bbpneo-dev-b1.svc.cluster.local:443/actuator/info"
        STAGE: "review"
        KANIKO_IMAGE_TAG: "${CI_COMMIT_REF_NAME}-dev-b1-$CI_COMMIT_SHORT_SHA"
        NAMESPACE: "dev-b1"
  trigger:
    include:
      - project: "cnp/bbpneo/02-ops/moqap"
        ref: "$CURRENT_VERSION"
        file: "/pipelines/pipeline.yaml"
    strategy: depend

Renovate:
  stage: dev
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != "development"  && $CI_COMMIT_BRANCH !~ /^Release/ && ($CI_COMMIT_BRANCH =~ /^renovate/ || $CI_COMMIT_BRANCH =~ /^renovate/ ) && $CI_COMMIT_TAG == null && $IS_COMMONLIB == "false" && $BIZHUB_DEPLOY_ONLY == "false" && $IMAGE_UPDATE == "false"
      when: always
      variables:
        DEPLOY_ENV: "int"
        STAGE_ENV: "dev"
        LAP_TEST_DISABLE: "false"
        TRIGGER_BUILD_MANUALLY: "false"
        PROJECT_RUNNER_TAG: "eks-integration"
        VERSION_ENV: "${CI_PROJECT_NAME}-${DEPLOY_ENV}"
        BASE_SERVICE_URL: "https://${VERSION_ENV}.bbpneo-iat.cnp-test.comp.db.de"
        SERVICE_URL: "https://${VERSION_ENV}.bbpneo-int.svc.cluster.local:443/actuator/info"
        SONARQUBE_PROJECT_KEY: "${CI_PROJECT_NAME}---Masterbranch"
  trigger:
    include:
      - project: "cnp/bbpneo/02-ops/moqap"
        ref: "$CURRENT_VERSION"
        file: "/pipelines/environments/int/release-build.yaml"
    strategy: depend

Renovate CommonLibs:
  stage: dev
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != "development"  && $CI_COMMIT_BRANCH !~ /^Release/ && ($CI_COMMIT_BRANCH =~ /^renovate/ || $CI_COMMIT_BRANCH =~ /^renovate/ ) && $CI_COMMIT_TAG == null && $IS_COMMONLIB == "true" && $BIZHUB_DEPLOY_ONLY == "false" && $IMAGE_UPDATE == "false"
      when: always
      variables:
        DEPLOY_ENV: "dev"
        STAGE_ENV: "dev"
        PROJECT_RUNNER_TAG: "eks-entwicklung"
        IS_COMMONLIB: "true"
        SONARQUBE_PROJECT_KEY: "${CI_PROJECT_NAME}"
  trigger:
    include:
      - project: "cnp/bbpneo/02-ops/moqap"
        ref: "$CURRENT_VERSION"
        file: "/pipelines/commonLibs/environment.yaml"
    strategy: depend

Pipeline will not run:
  stage: dev
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH  != "development"  && $CI_COMMIT_BRANCH  !~ /^Release/ && $CI_COMMIT_BRANCH !~ /^BBPT4/ && $CI_COMMIT_BRANCH !~ /^BABEDAS/ && $CI_COMMIT_BRANCH !~ /^BBPT7/ && $CI_COMMIT_BRANCH !~ /^BONE/ && $CI_COMMIT_BRANCH !~ /^renovate/ && $CI_COMMIT_TAG == null
      when: always
  trigger:
    include:
      - project: "cnp/bbpneo/02-ops/moqap"
        ref: "$CURRENT_VERSION"
        file: "/pipelines/stop.yaml"
    strategy: depend

Integrationstestumgebung:
  stage: int
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH  == "development" && $CI_COMMIT_TAG == null && $IS_COMMONLIB == "false" && $BIZHUB_DEPLOY_ONLY == "false"
      when: always
      variables:
        BIZHUB_DISABLE: "${INT_BIZHUB_DISABLE}"
        BIZHUB_VISIBILITY_TYPE: "${INT_BIZHUB_VISIBILITY_TYPE}"
        BIZHUB_VISIBILITY_ORGS: "${INT_BIZHUB_VISIBILITY_ORGS}"
        BIZHUB_SUBSCRIBE_ORGS: "${INT_BIZHUB_SUBSCRIBE_ORGS}"
        DEPLOY_ENV: "int"
        STAGE_ENV: "dev"
        LAP_TEST_DISABLE: "false"
        TRIGGER_BUILD_MANUALLY: "false"
        PROJECT_RUNNER_TAG: "eks-integration"
        VERSION_ENV: "${CI_PROJECT_NAME}-${DEPLOY_ENV}"
        BASE_SERVICE_URL: "https://${VERSION_ENV}.bbpneo-iat.cnp-test.comp.db.de"
        SERVICE_URL: "https://${VERSION_ENV}.bbpneo-int.svc.cluster.local:443/actuator/info"
        STAGE: "manual"
        KANIKO_IMAGE_TAG: "${CI_COMMIT_REF_NAME}-${DEPLOY_ENV}-${CI_COMMIT_SHORT_SHA}"
  trigger:
    include:
      - project: "cnp/bbpneo/02-ops/moqap"
        ref: "$CURRENT_VERSION"
        file: "/pipelines/pipeline.yaml"
    strategy: depend

Release:
  stage: int
  needs:
    - job: Integrationstestumgebung
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH  == "development" && $CI_COMMIT_TAG == null && $IS_COMMONLIB == "false" && $BIZHUB_DEPLOY_ONLY == "false" && $IMAGE_UPDATE == "false"
      when: always
      variables:
        PROJECT_RUNNER_TAG: "eks-integration"
  trigger:
    include:
      - project: "cnp/bbpneo/02-ops/moqap"
        ref: "$CURRENT_VERSION"
        file: "/pipelines/environments/int/release.yaml"
    strategy: depend

Release CommonLibs:
  stage: int
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH  == "development" && $CI_COMMIT_TAG == null && $IS_COMMONLIB == "true" && $GITLAB_USER_LOGIN != "techuser-duflor0011"
      when: always
      variables:
        IS_COMMONLIB: "true"
        DEPLOY_ENV: "dev"
        STAGE_ENV: "dev"
        IS_RELEASE: "true"
        CI_REGISTRY: "cna-bbpneo-commonlibs-maven-stage-local.bahnhub.tech.rz.db.de"
        PROJECT_RUNNER_TAG: "eks-entwicklung"
        SONARQUBE_PROJECT_KEY: "${CI_PROJECT_NAME}"
        GIT_REPO_SSH_URL: "${GIT_REPO_SSH_URL}"
  trigger:
    include:
      - project: "cnp/bbpneo/02-ops/moqap"
        ref: "$CURRENT_VERSION"
        file: "/pipelines/commonLibs/environment-release.yaml"
    strategy: depend

Release-Build:
  stage: int
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH  =~ /^Release/ && $CI_COMMIT_TAG == null && $IS_COMMONLIB == "false" && $BIZHUB_DEPLOY_ONLY == "false" && $IMAGE_UPDATE == "false"
      when: always
      variables:
        DEPLOY_ENV: "int"
        STAGE_ENV: "dev"
        LAP_TEST_DISABLE: "false"
        TRIGGER_BUILD_MANUALLY: "false"
        PROJECT_RUNNER_TAG: "eks-integration"
        VERSION_ENV: "${CI_PROJECT_NAME}-${DEPLOY_ENV}"
        BASE_SERVICE_URL: "https://${VERSION_ENV}.bbpneo-iat.cnp-test.comp.db.de"
        SERVICE_URL: "https://${VERSION_ENV}.bbpneo-int.svc.cluster.local:443/actuator/info"
        SONARQUBE_PROJECT_KEY: "${CI_PROJECT_NAME}---Masterbranch"
        KANIKO_IMAGE_TAG: "${CI_COMMIT_REF_NAME}-${DEPLOY_ENV}-${CI_COMMIT_SHORT_SHA}"
  trigger:
    include:
      - project: "cnp/bbpneo/02-ops/moqap"
        ref: "$CURRENT_VERSION"
        file: "/pipelines/environments/int/release-build.yaml"
    strategy: depend

Abnahmetestumgebung:
  stage: au
  needs:
    - job: Release-Build
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH  =~ /^Release/ && $CI_COMMIT_TAG == null && $IS_COMMONLIB == "false" && $BIZHUB_DEPLOY_ONLY == "false" && $IMAGE_UPDATE == "false"
      when: always
  trigger:
    include: /pipelines/au/environment.yaml
    strategy: depend

LUP-Umgebung:
  stage: lup
  needs:
    - job: Release-Build
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH  =~ /^Release/ && $CI_COMMIT_TAG == null && $IS_COMMONLIB == "false" && $BIZHUB_DEPLOY_ONLY == "false" && $IMAGE_UPDATE == "false"
      when: always
  trigger:
    include: /pipelines/lup/environment.yaml
    strategy: depend

Produktionsumgebung:
  stage: prod
  needs:
    - job: Abnahmetestumgebung
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH  =~ /^Release/ && $CI_COMMIT_TAG == null && $IS_COMMONLIB == "false" && $BIZHUB_DEPLOY_ONLY == "false" && $IMAGE_UPDATE == "false"
      when: always
  trigger:
    include: /pipelines/prod/environment.yaml
    strategy: depend

Bizhub-Deployment:
  stage: bizhub
  rules:
    - if: $BIZHUB_DEPLOY_ONLY == "true" && $CI_COMMIT_BRANCH  == "development"
      when: always
      variables:
        # dev
        DEV_BIZHUB_VISIBILITY_TYPE: "${DEV_BIZHUB_VISIBILITY_TYPE}"
        DEV_BIZHUB_VISIBILITY_ORGS: "${DEV_BIZHUB_VISIBILITY_ORGS}"
        DEV_BIZHUB_SUBSCRIBE_ORGS: "${DEV_BIZHUB_SUBSCRIBE_ORGS}"
        # dev-b1
        DEV_B1_BIZHUB_VISIBILITY_TYPE: "${DEV_B1_BIZHUB_VISIBILITY_TYPE}"
        DEV_B1_BIZHUB_VISIBILITY_ORGS: "${DEV_B1_BIZHUB_VISIBILITY_ORGS}"
        DEV_B1_BIZHUB_SUBSCRIBE_ORGS: "${DEV_B1_BIZHUB_SUBSCRIBE_ORGS}"
        # int
        INT_BIZHUB_VISIBILITY_TYPE: "${INT_BIZHUB_VISIBILITY_TYPE}"
        INT_BIZHUB_VISIBILITY_ORGS: "${INT_BIZHUB_VISIBILITY_ORGS}"
        INT_BIZHUB_SUBSCRIBE_ORGS: "${INT_BIZHUB_SUBSCRIBE_ORGS}"
        # au
        AU_BIZHUB_VISIBILITY_TYPE: "${AU_BIZHUB_VISIBILITY_TYPE}"
        AU_BIZHUB_VISIBILITY_ORGS: "${AU_BIZHUB_VISIBILITY_ORGS}"
        AU_BIZHUB_SUBSCRIBE_ORGS: "${AU_BIZHUB_SUBSCRIBE_ORGS}"
        # lup
        LUP_BIZHUB_VISIBILITY_TYPE: "${LUP_BIZHUB_VISIBILITY_TYPE}"
        LUP_BIZHUB_VISIBILITY_ORGS: "${LUP_BIZHUB_VISIBILITY_ORGS}"
        LUP_BIZHUB_SUBSCRIBE_ORGS: "${LUP_BIZHUB_SUBSCRIBE_ORGS}"
        # prod
        PROD_BIZHUB_VISIBILITY_TYPE: "${PROD_BIZHUB_VISIBILITY_TYPE}"
        PROD_BIZHUB_VISIBILITY_ORGS: "${PROD_BIZHUB_VISIBILITY_ORGS}"
        PROD_BIZHUB_SUBSCRIBE_ORGS: "${PROD_BIZHUB_SUBSCRIBE_ORGS}"
  trigger:
    include:
      - project: "cnp/bbpneo/02-ops/moqap"
        ref: "$CURRENT_VERSION"
        file: "/pipelines/stages/deploy-bizhub-only.yaml"
    strategy: depend
  allow_failure: true

Image-Update:
  stage: image-update
  rules:
    - if: $IMAGE_UPDATE == "true" && $CI_COMMIT_BRANCH  =~ /^Release/ && $DEPLOY_ENV == "au" && $STAGE_ENV == "au"
      when: always
      variables:
        IMAGE_UPDATE: "true"
        DEPLOY_ENV: "au"
        STAGE_ENV: "au"
        PROJECT_RUNNER_TAG: "eks-abnahme"
    - if: $IMAGE_UPDATE == "true" && $CI_COMMIT_BRANCH  =~ /^Release/ && $DEPLOY_ENV == "prod" && $STAGE_ENV == "prod"
      when: always
      variables:
        IMAGE_UPDATE: "true"
        DEPLOY_ENV: "prod"
        STAGE_ENV: "prod"
        PROJECT_RUNNER_TAG: "eks-produktion"
    - if: $IMAGE_UPDATE == "true" && $CI_COMMIT_BRANCH  == "development"
      when: always
      variables:
        IMAGE_UPDATE: "true"
  trigger:
    include:
      - project: "cnp/bbpneo/02-ops/moqap"
        ref: "$CURRENT_VERSION"
        file: "/pipelines/stages/image-update.yaml"
    strategy: depend
