---
include:
  - project: "moqap/modules"
    ref: "11.4.0"
    file:
      - "/eks/kaniko/kaniko.yml"
      - "/trivy/trivy.yml"
  - "/pipelines/settings.yaml"
  - "/pipelines/stages/build-python-image.yaml"
  - "/pipelines/stages/deployment.yaml"
  - "/pipelines/trivy/trivy.yaml"
  - "/pipelines/security/syft.yaml"
  - "/pipelines/security/grant.yaml"
  - "/pipelines/security/grype.yaml"
  - "/pipelines/defectDojo/defect-dojo.yaml"

variables:
  BUILD: "PYTHON"
  PROJECT_RUNNER_TAG: "eks-abnahme"
  DEPLOY_ENV: "au"
  STAGE_ENV: "au"
  KANIKO_IMAGE_TAG: "${CI_COMMIT_REF_NAME}-au-$CI_COMMIT_SHORT_SHA"
  CI_REGISTRY: "${AU_DOCKER_REPO}.bahnhub.tech.rz.db.de"
  IMAGE_UPDATE: "false"

stages:
  - .pre
  - build-image
  - security-scan
  - argo-cd-deploy
  - report-upload
  - .post

Print Variables:
  stage: build-image
  tags:
    - $PROJECT_RUNNER_TAG
  image: ${PROD_DOCKER_REPO}.bahnhub.tech.rz.db.de/basis-pipeline-image:version-3
  script:
    - echo $DEPLOY_ENV
    - echo $STAGE_ENV
    - echo $PROJECT_RUNNER_TAG
    - echo $KANIKO_IMAGE_TAG
    - echo $NAMESPACE
    - echo $CI_COMMIT_BRANCH
    - echo $IMAGE_UPDATE
