---
include:
  - project: "moqap/modules"
    ref: "11.4.0"
    file:
      - "/eks/kaniko/kaniko.yml"
      - "/trivy/trivy.yml"
  - "/pipelines/settings.yaml"
  - "/pipelines/stages/build-python-image.yaml"
  - "/pipelines/stages/deployment.yaml"
  - "/pipelines/trivy/trivy.yaml"
  - "/pipelines/security/syft.yaml"
  - "/pipelines/security/grant.yaml"
  - "/pipelines/security/grype.yaml"
  - "/pipelines/defectDojo/defect-dojo.yaml"

variables:
  BUILD: "PYTHON"
  PROJECT_RUNNER_TAG: "eks-abnahme"
  DEPLOY_ENV: "au"
  STAGE_ENV: "au"
  KANIKO_IMAGE_TAG: "${CI_COMMIT_REF_NAME}-au-$CI_COMMIT_SHORT_SHA"

stages:
  - .pre
  - build-image
  - security-scan
  - argo-cd-deploy
  - report-upload
  - .post
