---
variables:
  PROJECT_NAME: $CI_PROJECT_NAME
  PREFIX_CI_DEPLOYMENT_NAME: $PROJECT_NAME
  DEV_HELM: "./child-pipelines/${DEPLOY_ENV}/values-${DEPLOY_ENV}.yaml"
  # HTTP PROXY
  HTTP_PROXY_HOST: "webproxy.comp.db.de"
  HTTP_PROXY_PORT: "8080"
  HTTP_NON_PROXY_HOSTS: ".tech.rz.db.de,.rz.db.de,.amazon.com,.amazonaws.com,.aws.db.de,.cluster.local,.comp.db.de,.dbcs.db.de,.internal,.intranet-test.deutschebahn.com,.intranet.deutschebahn.com,.mail.db.de,.ose.db.de,.rz.db.de,.svc,.unix.db.de,10.193.0.1,127.0.0.1,169.254.169.254,dbcs-Maste-C6UND8OK4HFR-3e69d5b84ddd5126.elb.eu-central-1.amazonaws.com,ip-10-107-227-150.eu-central-1.compute.internal,localhost"
  # MVN
  JVM_HTTP_NON_PROXY_HOSTS: "*.tech.rz.db.de|*.rz.db.de|*.dbcs.db.de|*.amazonaws.com|*.aws.db.de|*.cluster.local|*.internal|*.intranet-test.deutschebahn.com|*.intranet.deutschebahn.com|*.mail.db.de|*.ose.db.de|*.rz.db.de|*.svc|*.unix.db.de|127.0.0.1|dbcs-Maste-C6UND8OK4HFR-3e69d5b84ddd5126.elb.eu-central-1.amazonaws.com|ip-10-107-227-150.eu-central-1.compute.internal|localhost"
  GRADLE_OPTS_OWN: "-Xdebug -XshowSettings -Xdiag  -Dhttps.proxyHost=webproxy.comp.db.de -Dhttps.proxyPort=8080 -Dhttp.nonProxyHosts=*.tech.rz.db.de|*.dbcs.db.de|*.amazonaws.com|*.aws.db.de|*.cluster.local|*.internal|*.intranet-test.deutschebahn.com|*.intranet.deutschebahn.com|*.mail.db.de|*.ose.db.de|*.rz.db.de|*.svc|*.unix.db.de|127.0.0.1|dbcs-Maste-C6UND8OK4HFR-3e69d5b84ddd5126.elb.eu-central-1.amazonaws.com|ip-10-107-227-150.eu-central-1.compute.internal|localhost|*.comp.db.de"
  #Upload image
  CI_REGISTRY: "${DEV_DOCKER_REPO}.bahnhub.tech.rz.db.de"
  CI_REGISTRY_USER: $ARTIFACTORY_USER
  CI_REGISTRY_PASSWORD: $ARTIFACTORY_PASSWORD
  #TRIVY 
  TRIVY_USERNAME: $ARTIFACTORY_USER
  TRIVY_PASSWORD: $ARTIFACTORY_PASSWORD
  TRIVY_TARGET: "$CI_REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$DEPLOY_ENV-$CI_COMMIT_SHORT_SHA"
  #LIQUIBASE
  LIQUIBASE_DISABLE: "true"
  FIELD_DB_URL: "database-url"
  FIELD_DB_USER: "database-user"
  FIELD_DB_PASSWORD: "database-password"
  #BIZHUB
  BIZHUB_DISABLE: "true"
  BIZHUB_CONNECT_CONFIG: ""
