---
include:
  # Generic pipeline description for all stages
  - "pipelines/pipeline.yaml"

# Stage-specific variables
variables:
  STAGE_ENV: "dev"
  LAP_TEST_DISABLE: "true"
  TRIGGER_BUILD_MANUALLY: "true"
