---
include:
  # Generic pipeline description for all stages
  - "pipelines/pipeline.yaml"

# Stage-specific variables
variables:
  DEPLOY_ENV: "dev"
  STAGE_ENV: "dev"
  LAP_TEST_DISABLE: "true"
  TRIGGER_BUILD_MANUALLY: "true"
  PROJECT_RUNNER_TAG: "eks-entwicklung"
  VERSION_ENV: "${CI_PROJECT_NAME}-${DEPLOY_ENV}"
  BASE_SERVICE_URL: "https://${VERSION_ENV}.bbpneo-iat.cnp-test.comp.db.de"
  SERVICE_URL: "https://${VERSION_ENV}.bbpneo-dev-babedas.svc.cluster.local:443/actuator/info"
  STAGE: "review"
  BIZHUB_DISABLE: "$DEV_BIZHUB_DISABLE"
  BIZHUB_VISIBILITY_TYPE: "$DEV_BIZHUB_VISIBILITY_TYPE"
  BIZHUB_VISIBILITY_ORGS: "$DEV_BIZHUB_VISIBILITY_ORGS"
  BIZHUB_SUBSCRIBE_ORGS: "$DEV_BIZHUB_SUBSCRIBE_ORGS"
