---
include:
  # Generic pipeline description for all stages
  - "pipelines/pipeline.yaml"

# Stage-specific variables
variables:
  DEPLOY_ENV: "dev"
  STAGE_ENV: "dev"
  LAP_TEST_DISABLE: "true"
  TRIGGER_BUILD_MANUALLY: "true"
  PROJECT_RUNNER_TAG: "eks-entwicklung"
  BIZHUB_CONNECT_CONFIG: "pipelines/dev/bizhub/connect.yaml"
  BASE_SERVICE_URL: "https://${CI_PROJECT_NAME}-dev.bbpneo-iat.cnp-test.comp.db.de"
  SERVICE_URL: "https://${CI_PROJECT_NAME}-dev.bbpneo-dev-babedas.svc.cluster.local:443/actuator/info"