rules:
  ###### BBPNeo
  - pattern: https://github.com/corretto/corretto-jdk/blob/develop/LICENSE
    mode: "allow"
    name: https://github.com/corretto/corretto-jdk/blob/develop/LICENSE
    reason: AWS GNU General Public License (GPL)
  - pattern: "https://h2database.com/html/license.html"
    mode: "allow"
    name: Eclipse Public License 1.0
    reason: EPL-1.0 whitelisted by default preset
  - pattern: "https://www.antlr.org/license.html"
    mode: "allow"
    name: BSD Zero Clause License
    reason: 0BSD whitelisted by default preset
  - pattern: "WITH"
    mode: "allow"
    name: GNU Wget
    reason: GNU Wget is a free software package
  - pattern: "https://github.com/stleary/JSON-java/blob/master/LICENSE"
    mode: "allow"
    name: JSON-java
    reason: Public Domain
  - pattern: "LICENSE"
    mode: "allow"
    name: ehcache-107
    reason: Apache 2.0 whitelisted by default preset
  - pattern: "The Apache License, Version 2.0"
    mode: "allow"
    name: Apache License 2.0:Apache 2.0
    reason: Apache 2.0 whitelisted by default preset
  - pattern: "http://www.apache.org/licenses/LICENSE-2.0.txt"
    mode: "allow"
    name: Apache License 2.0:Apache 2.0
    reason: Apache 2.0 whitelisted by default preset
  - pattern: "https://www.apache.org/licenses/LICENSE-2.0.txt"
    mode: "allow"
    name: Apache License 2.0:Apache 2.0
    reason: Apache 2.0 whitelisted by default preset
  - pattern: "http://apache.org/licenses/LICENSE-2.0"
    mode: "allow"
    name: Apache License 2.0:Apache 2.0
    reason: Apache 2.0 whitelisted by default preset
  - pattern: "https://www.apache.org/licenses/LICENSE-2.0"
    mode: "allow"
    name: Apache License 2.0:Apache 2.0
    reason: Apache 2.0 whitelisted by default preset
  - pattern: "http://www.apache.org/licenses/LICENSE-2.0"
    mode: "allow"
    name: Apache License 2.0:Apache 2.0
    reason: Apache 2.0 whitelisted by default preset
  - pattern: "\"Apache-2.0\";link=\"https://www.apache.org/licenses/LICENSE-2.0.txt\""
    mode: "allow"
    name: Apache License 2.0:Apache 2.0
    reason: Apache 2.0 whitelisted by default preset
  - pattern: "\"Apache License 2.0\";link=\"http://www.apache.org/licenses/LICENSE-2.0.html\""
    mode: "allow"
    name: Apache License 2.0:Apache 2.0
    reason: Apache 2.0 whitelisted by default preset
  - pattern: "http://www.apache.org/licenses/LICENSE-2.0, http://www.slf4j.org/license.html"
    mode: "allow"
    name: Apache License 2.0:Apache 2.0
    reason: Apache 2.0 whitelisted by default preset
  - pattern: "https://repository.jboss.org/licenses/apache-2.0.txt"
    mode: "allow"
    name: Apache License 2.0:Apache 2.0
    reason: Apache 2.0 whitelisted by default preset
  - pattern: "X11*"
    mode: "allow"
    name: MIT License
    reason: This is same as MIT, but with no advertising clause added
  - pattern: "OpenSSL-Exception"
    mode: "allow"
    name: wget
    reason: GNU Wget is a free software package
  - pattern: "WITH"
    mode: "allow"
    name: wget
    reason: GNU Wget is a free software package
  - pattern: "http://www.eclipse.org/legal/epl-2.0, http://www.eclipse.org/org/documents/edl-v10.php"
    mode: "allow"
    name: Eclipse Public License 2.0:EPL-2.0
    reason: EPL-2.0 whitelisted by default preset
  - pattern: "http://www.eclipse.org/legal/epl-v10.html, http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html"
    mode: "allow"
    name: Eclipse Public License 1.0
    reason: EPL-1.0 whitelisted by default preset
  - pattern: "http://www.eclipse.org/legal/epl-2.0, https://www.gnu.org/software/classpath/license.html"
    mode: "allow"
    name: Eclipse Public License 2.0:EPL-2.0
    reason: EPL-2.0 whitelisted by default preset
  - pattern: "BSD-3-Clause;link=https://asm.ow2.io/LICENSE.txt"
    mode: "allow"
    name: BSD 3-Clause License
    reason: BSD-3-Clause whitelisted by default preset
  - pattern: "http://www.opensource.org/licenses/mit-license.php"
    mode: "allow"
    name: MIT License
    reason: This is same as MIT, but with no advertising clause added
  - pattern: "Public Domain, per Creative Commons CC0"
    mode: "allow"
    name: CC0 Lizenz
    reason: Public Domain
  - pattern: "http://creativecommons.org/publicdomain/zero/1.0/, https://opensource.org/licenses/BSD-2-Clause"
    mode: "allow"
    name: BSD 2-Clause "Simplified" License
    reason: BSD-2-Clause whitelisted by default preset
  - pattern: "https://oss.oracle.com/licenses/CDDL+GPL-1.1, https://oss.oracle.com/licenses/CDDL+GPL-1.1"
    mode: "allow"
    name: GNU General Public License only
    reason: GPL whitelisted by default preset
  - pattern: "http://www.eclipse.org/org/documents/edl-v10.php"
    mode: "allow"
    name: BSD 3-Clause
    reason: BSD-3-Clause whitelisted by default preset
